name: Test Suite
on: [push, pull_request]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Run backend tests
      run: npm run test:backend
      env:
        JWT_SECRET: test-secret
        FIREBASE_PROJECT_ID: test-project
        PORT: 5000

  test-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Run frontend tests
      run: npm run test:frontend
      env:
        CI: true

  test-e2e:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Run Cypress tests
      run: npx cypress run
      env:
        CYPRESS_BASE_URL: http://localhost:3000